### ISSUE TITLE
论文中POS-Guided Phrasal Segmentation部分是否加入项目呢？

### ISSUE THREAD

**Issue by lj976264709** [luozhouyang/AutoPhraseX#11]
阅读后，发现代码更新随机森林分类器后直接对候选集进行分类。POS-Guided Phrasal Segmentation是否是必要的环节呢？相比原论文jieba中的HMM会提升一点性能嘛？恳请得到回答，非常感谢！！

**Comment by luozhouyang** [comment]
POS-Guided Phrasal Segmentation因为引入了额外的信息，理论上是有帮助的。我觉得远论文的POS比较麻烦所以没加上去。你可以做一下对比实验。
